version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - GRPC_LISTENER_PORT=8080
      - REDIS_ADDRESS=:6379
    depends_on:
      - db
    networks:
      - backend
  db:
    hostname: db
    image: "postgres"
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -d postgres
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - backend
  migrate:
    image: migrate/migrate
    networks:
      - backend
    volumes:
      - ./db/migrations:/migrations
#    command: [ "-path", "migrations", "-database",  "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable", "-verbose", "down", "-all" ]
    command: [ "-path", "migrations", "-database",  "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable", "-verbose", "up" ]
    depends_on:
      - db
    links:
      - db

volumes:
  db:
    driver: local

networks:
  backend:
    driver: bridge
