// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type User struct {
	ID             int64        `json:"id"`
	Uuid           string       `json:"uuid"`
	Firstname      string       `json:"firstname"`
	Lastname       string       `json:"lastname"`
	Email          string       `json:"email"`
	HashedPassword string       `json:"hashed_password"`
	Verified       sql.NullBool `json:"verified"`
	Created        time.Time    `json:"created"`
}
