// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByUUID(ctx context.Context, uuid string) (User, error)
	SetUserVerified(ctx context.Context, id int64) error
	UserEmailExists(ctx context.Context, email string) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
